#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/njmarzina/.vscode-server/bin/848b80aeb52026648a8ff9f7c45a9b0a80641e2e/node" "/home/njmarzina/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"